name: tests

run-name: testing in node

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
          npm run lint
          npx playwright install --with-deps
        env:
          CI: true
      - name: Run tests
        run: |
          xvfb-run --server-args="-screen 0 1920x1080x24" npm test
